name = "CTDiffFlow"
uuid = "110d5101-4da8-4772-9137-015210ab14e3"
version = "0.1.0"
authors = ["Olivier Cots <olivier.cots@toulouse-inp.fr>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
DualNumbers = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
ODEInterface = "54ca160b-1b9f-5127-a996-1867f4bc2a2c"
ODEInterfaceDiffEq = "09606e27-ecf5-54fc-bb29-004bd9f985bf"
ODEProblemLibrary = "fdc4e326-1af4-4b90-96e7-779fcce2daa5"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
BenchmarkTools = "1.6.3"
DiffEqDevTools = "2.48.0"
DifferentiationInterface = "0.7.9"
DualNumbers = "0.6.9"
Enzyme = "0.13.88"
ForwardDiff = "1.2.2"
LaTeXStrings = "1.4.0"
LinearAlgebra = "1.12.0"
Mooncake = "0.4.202"
ODEInterface = "0.5.0"
ODEInterfaceDiffEq = "3.13.5"
ODEProblemLibrary = "1.2.2"
OrdinaryDiffEq = "6.102.1"
Plots = "1.41.1"
Revise = "3.13.2"
SciMLSensitivity = "7.90.0"
Zygote = "0.7.10"
julia = "1.11"
